name = "cmdexe-is-here"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "cmdexe-is-here_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "cmdexe-is-here.wasm"
command = "npm run build:release"
